### ISSUE TITLE
Unexpected status SERVICE_STOPPED in response to START control.

### ISSUE THREAD

**Issue by SiberMedya** [nono303/memcached#10]
memcached: Unexpected status SERVICE_STOPPED in response to START control.

libevent-2.1 x64
memcached v1.6.17.0
windows 2022 x64

`nssm-2.25.0.exe install memcached C:\memcached\memcached-avx.exe
nssm-2.25.0.exe set memcached AppParameters "-vv -m 512 -I 256m"
nssm-2.25.0.exe set memcached AppDirectory C:\memcached
nssm-2.25.0.exe set memcached AppExit Default Restart
nssm-2.25.0.exe set memcached AppNoConsole 1
nssm-2.25.0.exe set memcached AppPriority ABOVE_NORMAL_PRIORITY_CLASS
nssm-2.25.0.exe set memcached AppStderr C:\memcached\logs\memcached.log
nssm-2.25.0.exe set memcached AppStopMethodSkip 6
nssm-2.25.0.exe set memcached AppTimestampLog 1
nssm-2.25.0.exe set memcached DisplayName memcached
nssm-2.25.0.exe set memcached ObjectName LocalSystem
nssm-2.25.0.exe set memcached Start SERVICE_AUTO_START
nssm-2.25.0.exe set memcached Type SERVICE_WIN32_OWN_PROCESS`

**Comment by nono303** [comment]
Hi @SiberMedya 
Can you launch it in `-vvv` and drop content of `C:\memcached\logs\memcached.log `

**Comment by SiberMedya** [comment]
> Hi @SiberMedya Can you launch it in `-vvv` and drop content of `C:\memcached\logs\memcached.log `

i create logs folder and service stared
thanks
