### ISSUE TITLE
Use as a service

### ISSUE THREAD

**Issue by marcoas** [nono303/memcached#4]
Hi.

Is it possible to install it as a service in windows 10?
To make sure it runs on every computer startup.

Thanks.

**Comment by nono303** [comment]
Hi @marcoas,
I personally use [nssm](https://nssm.cc/) with this config:

```
nssm.exedump memcached

nssm.exeinstall memcached C:\memcached\memcached-avx.exe
nssm.exeset memcached AppParameters "-vv -m 512 -I 256m"
nssm.exeset memcached AppDirectory C:\memcached
nssm.exeset memcached AppExit Default Restart
nssm.exeset memcached AppNoConsole 1
nssm.exeset memcached AppPriority ABOVE_NORMAL_PRIORITY_CLASS
nssm.exeset memcached AppStderr C:\memcached\logs\memcached.log
nssm.exeset memcached AppStopMethodSkip 6
nssm.exeset memcached AppTimestampLog 1
nssm.exeset memcached DisplayName memcached
nssm.exeset memcached ObjectName LocalSystem
nssm.exeset memcached Start SERVICE_AUTO_START
nssm.exeset memcached Type SERVICE_WIN32_OWN_PROCESS
```

**Comment by SiberMedya** [comment]
> Hi @marcoas, I personally use [nssm](https://nssm.cc/) with this config:
> 
> ```
> nssm.exedump memcached
> 
> nssm.exeinstall memcached C:\memcached\memcached-avx.exe
> nssm.exeset memcached AppParameters "-vv -m 512 -I 256m"
> nssm.exeset memcached AppDirectory C:\memcached
> nssm.exeset memcached AppExit Default Restart
> nssm.exeset memcached AppNoConsole 1
> nssm.exeset memcached AppPriority ABOVE_NORMAL_PRIORITY_CLASS
> nssm.exeset memcached AppStderr C:\memcached\logs\memcached.log
> nssm.exeset memcached AppStopMethodSkip 6
> nssm.exeset memcached AppTimestampLog 1
> nssm.exeset memcached DisplayName memcached
> nssm.exeset memcached ObjectName LocalSystem
> nssm.exeset memcached Start SERVICE_AUTO_START
> nssm.exeset memcached Type SERVICE_WIN32_OWN_PROCESS
> ```

C:\memcached>nssm-2.25.0.exe start memcached
memcached: Unexpected status SERVICE_STOPPED in response to START control.
