### ISSUE TITLE
Couldn't stop process with `-d` arguments.

### ISSUE THREAD

**Issue by ve3** [nono303/memcached#5]
The commands below are run on administrator privilege.

First start with ` memcached.exe -vvv -d start` .
Returns 
> Nothing left to crawl for ...
LRU crawler thread sleeping

This seems to start working properly.

And then `memcached.exe -vvv -d stop`.
Returns 
> Starting LRU crawler background thread
Starting LRU maintainer background thread
failed to listen on TCP port 11211: Address already in use

Run the commands `memcached.exe -vvv -d uninstall`, `memcached.exe -vvv -d kill`, `memcached.exe -vvv -d end` return the same as above.
> Starting LRU crawler background thread
Starting LRU maintainer background thread
failed to listen on TCP port 11211: Address already in use

I have to kill process from task manager every time.

Is this normal?

**Comment by nono303** [comment]
Hi @ve3,
Yes, all is normal.
`-d` only means run as daemon (background) and didn't not accept command like start, stop, etc... referring to documentation.
You can not mange it as a service like this and and windows you might use [nssm](https://github.com/puppetlabs/nssm.git) to do it.
