### ISSUE TITLE
problem with cygwin on win server 2008r2

### ISSUE THREAD

**Issue by keybo111** [nono303/memcached#7]
I can't run memcached.
I get this error in memcached log:
0 [main] memcached-avx 1515 cygwin_exception::open_stackdumpfile: Dumping stack trace to memcached-avx.exe.stackdump

and in memcached-avx.exe.stackdump:
Exception: STATUS_ILLEGAL_INSTRUCTION at rip=00100428FF2
....

what can be wrong?

**Comment by nono303** [comment]
`STATUS_ILLEGAL_INSTRUCTION` > Try non avx version (see https://github.com/nono303/PHP-memcache-dll#how-to-get-the-good-version)

**Comment by keybo111** [comment]
Yes! of course. blindly following instructions make me failed. Thnx it's all up and running now.
