### ISSUE TITLE
Windows Memcached got error 0xc0000005

### ISSUE THREAD

**Issue by marcolungo** [nono303/memcached#9]
Hi,
I've installed Windows Memcached on Windows Server 2022 - Apache 2.54 - PHP 8.1.5
I got this error: [https://prnt.sc/hZuzzXPqNn9i](https://github.com/memcached/memcached/issues/url) [https://prnt.sc/ogQbC4H1zaGF](https://github.com/memcached/memcached/issues/url)
Maybe I've installed an older version? What is the correct one for my configuration?
Could anyone help me to understand and resolve the error?
Thank you!

**Comment by nono303** [comment]
Hi @marcolungo 
As show on your screen capture, Nothing to deal with memcached.exe

**Comment by marcolungo** [comment]
I'm sorry Nono303,
if you do not are involved in php_memcached.dll, please, could you let me know where is the correct place to post this error?
Thank You!

**Comment by nono303** [comment]
this project https://github.com/nono303/memcached is for memcached.exe
https://github.com/nono303/PHP-memcache-dll is for php_memcached.dll

**Comment by nono303** [comment]
please read CAREFULLY https://github.com/nono303/PHP-memcache-dll/blob/master/README.md#how-to-get-the-good-version before opening issue on https://github.com/nono303/PHP-memcache-dll as it always the same problem https://github.com/nono303/PHP-memcache-dll/issues?q=is%3Aissue+is%3Aclosed
